-- Migration script for Worklingo v2.0
-- Run this in your Supabase SQL Editor to add new fields

-- Add 'context' column for storing user provided context
ALTER TABLE analysis_records 
ADD COLUMN IF NOT EXISTS context TEXT;

-- Add 'tone' column for storing the requested tone (e.g., Formal, Friendly)
ALTER TABLE analysis_records 
ADD COLUMN IF NOT EXISTS tone VARCHAR(50);

-- Add 'polished_text' column for the AI polished version
ALTER TABLE analysis_records 
ADD COLUMN IF NOT EXISTS polished_text TEXT;

-- Add 'explanation' column for AI explanation
ALTER TABLE analysis_records 
ADD COLUMN IF NOT EXISTS explanation TEXT;

-- Create vocabulary excerpts table for context-based word capture
CREATE TABLE IF NOT EXISTS vocabulary_excerpts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    term TEXT NOT NULL,
    excerpt_text TEXT NOT NULL,
    context_sentence TEXT,
    source TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vocab_excerpts_user_term
ON vocabulary_excerpts(user_id, term);

-- Optional: Update existing records to have default values if needed
-- UPDATE analysis_records SET tone = 'Neutral' WHERE tone IS NULL;
